# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-25 17:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import works.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('cover_picture', models.ImageField(upload_to=works.models.upload_path, verbose_name='Cover Picture')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Content')),
                ('link', models.CharField(max_length=150, verbose_name='Link')),
                ('bgcolor', models.CharField(max_length=25, verbose_name='Background Color')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_of_work', to='works.WorkCategoryModel', verbose_name='Category')),
                ('tech', models.ManyToManyField(to='works.TechModel')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='WorkPicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to=works.models.upload_path, verbose_name='Cover Picture')),
                ('work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='picture_of_work', to='works.WorkModel', verbose_name='Work')),
            ],
        ),
    ]
