# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='workmodel',
            name='category',
            field=models.ManyToManyField(to='works.WorkCategoryModel'),
        ),
    ]
