# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-26 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_auto_20180526_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workpicmodel',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='works.WorkModel', verbose_name='Work'),
        ),
    ]
